<?php

namespace Bibli\LivresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeCommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCommentaireRepository extends EntityRepository
{
}
